### ISSUE TITLE
Create default workspace after registration

### ISSUE THREAD

**Issue by JakubJW** [JakubJW/trello-clone-backend#1]
The default workspace should have a board with some example columns and tasks. We need logic that would redirect user straight to that default workspace after successfull registration.

For now I'm not entirely sure how to handle it on the frontend, but I was thinking about obtaining current/default workspace field from `/me` endpoint and then I would be able to redirect user to appropriate view.

**Comment by OresFCK** [comment]
Done -> https://github.com/JakubJW/trello-clone-backend/pull/7
